######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 27 18:39:50 2012
######################################################################

TEMPLATE = app
TARGET = webapp
DEPENDPATH += .
INCLUDEPATH += .

QT += webkitwidgets network

# Input
HEADERS += webapp.h webpage.h cookiejar.h networkaccessmanager.h
SOURCES += main.cpp webapp.cpp webpage.cpp cookiejar.cpp networkaccessmanager.cpp

