######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 27 18:39:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += webkit network

# Input
HEADERS += webapp.h webpage.h
SOURCES += main.cpp webapp.cpp webpage.cpp

LIBS += -lqjson
